"""rename foto to profile_picture in users

Revision ID: 7f407b5a3821
Revises: d4ffcc0da6c1
Create Date: 2026-03-25 22:55:21.111233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f407b5a3821'
down_revision = 'd4ffcc0da6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
