"""Add current_index and question_ids to QuizSession

Revision ID: a86554a18684
Revises: e2aa76fcd867
Create Date: 2026-04-17 22:55:46.030909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86554a18684'
down_revision = 'e2aa76fcd867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_index', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('question_ids', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('question_ids')
        batch_op.drop_column('current_index')

    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
